# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_auto_20171216_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Movie.Director'),
            preserve_default=False,
        ),
    ]
